name: Create Release from Dispatch

on:
  repository_dispatch:
    types: [create_release]

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: BerichtsheftMakerUpdater-Exe
        path: ./ 

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.event.client_payload.tag_name }}
        release_name: ${{ github.event.client_payload.release_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./BerichtsheftMakerUpdater.exe
        asset_name: BerichtsheftMakerUpdater.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

