name: Re-release from private repository

on:
  repository_dispatch:
    types: [my-event]

jobs:
  download_and_release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout current repository
      - name: Checkout current repository
        uses: actions/checkout@v3

      # 2. Download the latest release asset from the private repository
      - name: Download release from private repository
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Tim-46/BerichtsheftMakerUpdater/releases/latest \
            | jq -r '.assets[0].browser_download_url' \
            | xargs curl -L -o asset.zip

      # 3. Create a new release in the current repository
      - name: Create new release in current repository
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: 'v${{ github.event.inputs.version }}'  # Beispiel: Festlegung der Version
          release_name: 'Re-release of the asset'
          body: 'This is a re-release of the asset from a private repository.'
          draft: false
          prerelease: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 4. Upload the downloaded asset to the new release
      - name: Upload the asset to the new release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./asset.zip
          asset_name: asset.zip
          asset_content_type: application/zip
