name: Create Release in Version Repo

on:
  repository_dispatch:
    types: [trigger_version_release]

jobs:
  download_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out version repository
      uses: actions/checkout@v2

    - name: Download Artifact from BerichtsheftMakerUpdater
      uses: actions/download-artifact@v2
      with:
        name: BerichtsheftMakerUpdater-Exe
        path: ./  # Download to the current directory

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./BerichtsheftMakerUpdater.exe
        asset_name: BerichtsheftMakerUpdater.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}


