name: Re-release .exe file

on:
  repository_dispatch:
  release:
    types: [my-event]

jobs:
  re_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Finde die Download-URL der .exe-Datei
        id: get_download_url
        run: |
          # Hole alle Assets des neuesten Releases
          ASSETS=$(curl -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Tim-46/BerichtsheftMakerUpdater/releases/latest \
            | jq -r '.assets[] | "\(.name) - \(.browser_download_url)"')
          
          echo "Available release assets:"
          echo "$ASSETS"
          
          # Finde die Download-URL der .exe-Datei
          DOWNLOAD_URL=$(curl -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Tim-46/BerichtsheftMakerUpdater/releases/latest \
            | jq -r '.assets[] | select(.name | endswith(".exe")).browser_download_url')
          
          echo "Download URL: $DOWNLOAD_URL"
          echo "::set-output name=download_url::$DOWNLOAD_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Lade die .exe-Datei herunter und zeige Debug-Informationen an
        run: |
          # Lade die .exe-Datei herunter
          curl -v -L -H "Authorization: token $GITHUB_TOKEN" "$DOWNLOAD_URL" -o BerichtsheftMakerUpdater.exe
          
          # Zeige die Dateigröße und den Dateityp an, um sicherzustellen, dass der Download erfolgreich war
          ls -lh BerichtsheftMakerUpdater.exe
          file BerichtsheftMakerUpdater.exe
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        shell: bash

      - name: Erstelle ein neues Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Re-release of the .exe file
          body: This is a re-release of the .exe file from a private repository.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Lade die .exe in das neue Release hoch
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./BerichtsheftMakerUpdater.exe
          asset_name: BerichtsheftMakerUpdater.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

