name: Download Artifact
on:
  workflow_run:
    workflows: ["Upload Artifact"]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: berichtsheft-artifact

      - name: Display artifact content
        run: |
          unzip berichtsheft-artifact/exe.zip
          ls berichtsheft-artifact/exe

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: berichtsheft-artifact/exe/*
          tag_name: v1.0
          release_name: BerichtsheftMakerUpdater v1.0
          body: "Release notes for BerichtsheftMakerUpdater v1.0"
          draft: false
          prerelease: false
          token: ${{ secrets.MY_GITHUB_TOKEN }}


