name: Create Release from Artifact

on:
  workflow_run:
    workflows: ["Build and Release to Version Repo"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Download Build Artifact from BerichtsheftMakerUpdater Repo
      uses: actions/download-artifact@v3  # Aktualisierung auf v3
      with:
        name: BerichtsheftMakerUpdater-Exe
        path: ./

    - name: Check if artifact exists
      run: |
        if [ ! -f "BerichtsheftMakerUpdater.exe" ]; then
          echo "Artifact not found!"
          exit 1
        fi
        echo "Artifact found!"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./BerichtsheftMakerUpdater.exe
        asset_name: BerichtsheftMakerUpdater.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
